### ISSUE TITLE
Page title is [object Object]

### ISSUE THREAD

**Issue by jenial** [Automattic/community-translator#2] opened 2016-01-14 13:22 UTC
When the Community Translator is on, the page title shows up as [object Object] - WordPress.com. We should preserve the original page title.

![_object_object__ _wordpress_com](https://cloud.githubusercontent.com/assets/7637835/12325375/1a567260-baca-11e5-9a7a-6c187acdc9cd.jpg)

**Comment by deBhal** [comment] 2016-01-15 01:07
I did a bit of digging, and the problem is in the calypso jumpstart, so I've opened the issue there

**Comment by akirk** [comment] 2016-01-18 10:40
Fixed in https://github.com/Automattic/wp-calypso/pull/2461

**Closed as completed by akirk** 2016-01-18 10:40 UTC
Labels: [Type] Bug
